schemaVersion: 2.2.0
metadata:
  generateName: jupyter-notebook-101
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/redhat-developer/devspaces-telemetry:latest
      memoryRequest: 1Gi
      memoryLimit: 8Gi
      cpuLimit: '4'
      cpuRequest: '0.5'

